config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :clientes
  resources :restaurantes

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  validates_presence_of :name, message: "Deve ser preenchido"

  validates_numericality_of :idade, greater_than: 0,
                                    less_than: 100,
                                    message: "Deve ser um número entre 0 e 100"
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base

validates_presence_of :name, message: "deve ser preenchido"

validates_presence_of :endereco, message: "deve ser preenchido"

validates_presence_of :especialidade, message: "deve ser preenchido"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:name, :idade)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:name, :endereco, :especialidade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'restaurant', :root, class: "navbar-brand" %>
    </div>
  </div>
</nav>

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clientes</h1>
</BR>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.id %></td>
        <td><%= cliente.name %></td>
        <td><%= cliente.idade %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td>
          <%= link_to 'Edit', edit_cliente_path(cliente) %>
      </td>
        <td>
          <%= button_to cliente, method: :delete, class: "btn btn-xs btn-danger" do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path, class:"btn btn-primary"%>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cliente.name %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @cliente.idade %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>

<h1> 1 Página do Projeto </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  </BR>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <h1>Sistema de Qualificação de Restaurantes !!!</h1>
    </div>
  </div>
</nav>

</BR>
    <div class="container">

      <%= link_to "Home", home_index_path, class:"btn btn-primary" %>

      <%= link_to "Restaurantes", restaurantes_path, class:"btn btn-success" %>

      <%= link_to "Clientes", clientes_path, class:"btn btn-info" %>

      <%= yield %>
    </div>
 <footer>
 </footer>

</body>
</html>

app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :especialidade %><br>
    <%= f.text_field :especialidade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurantes/edit.html.erb
<h1>Editing Restaurante</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurante %> |
<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurantes</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Endereco</th>
      <th>Especialidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= restaurante.id %></td>
        <td><%= restaurante.name %></td>
        <td><%= restaurante.endereco %></td>
        <td><%= restaurante.especialidade %></td>
        <td><%= link_to 'Show', restaurante %></td>
        <td><%= link_to 'Edit', edit_restaurante_path(restaurante) %></td>
        <td>
         <%= button_to restaurante, method: :delete, class: "btn btn-xs btn-danger" do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurante', new_restaurante_path, class:"btn btn-primary" %>

app/views/restaurantes/new.html.erb
<h1>New Restaurante</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurante.name %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @restaurante.endereco %>
</p>

<p>
  <strong>Especialidade:</strong>
  <%= @restaurante.especialidade %>
</p>

<%= link_to 'Edit', edit_restaurante_path(@restaurante) %> |
<%= link_to 'Back', restaurantes_path %>